public class StringDemo1 {
	public static void main(String[] args) {
		String s1 = new String("Hello");
		String s2 = new String("Hello");
		String s3 = "Hello";
		String s4 = "Hello";
		/*
			Hashcode is a unique code which is generated by the JVM for every object creation.
			Advantages of hashcode is it makes searching operation easy bcoz when we search for an object 
			that unique code helps to find out that obj.
			If two objects are equal, their hash code must also be equal
		*/
		System.out.println(s1.hashCode());
		System.out.println(s2.hashCode());
		System.out.println(s3.hashCode());
		System.out.println(s1==s2);
		System.out.println(s1==s3);
		System.out.println(s2==s3);
		System.out.println(s3==s4);
	}
}